export enum IUserEvents {
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  CREATE_TODO = 'CREATE_TODO',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  DELETE_TODO = 'DELETE_TODO',
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
}
